
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('bios').del()
    .then(function () {
      // Inserts seed entries
      return knex('bios').insert([
        {partner_id: 3, paragraph: "Charles J. Muchmore has broad and varied litigation and ADR experience that includes handling professional liability, personal injury, product liability, construction, insurance coverage, and commercial litigation matters. Mr. Muchmore has been certified as an Injury and Wrongful Death Litigation Specialist by the Arizona Board of Legal Specialization since 1991. He has been listed in Southwest Super Lawyers since 2009, is included among Arizona’s Finest Lawyers and is an AV® Preeminent 5.0 out of 5.0 peer review rated attorney in Martindale-Hubbell. He is a member of the National Academy of Distinguished Neutrals. " },

        {partner_id: 3, paragraph: "Due to his extensive courtroom experience, Mr. Muchmore was selected as a member of the faculty of the Trial Academy of the International Association of Defense Counsel (IADC). He also has been a featured speaker on toxic tort matters at seminars sponsored by the IADC, the Association of Trial Lawyers of America, the State Bar of Arizona, the Arizona Trial Lawyers Association and the Maricopa County Bar Association. He is lead author of the chapter on \"Manager, Shareholder, Officer and Director Liability\" in the Arizona Environmental Law Manual. Mr. Muchmore served as editor for toxic tort and insurance issues of the State Bar's environmental law newsletter and is past chair of a State Bar seminar on toxic tort litigation. Mr. Muchmore has been a leader in the use of technology in the practice of law and has been appointed as a special master in discovery of electronically stored information. " },

        {partner_id: 3, paragraph: "Mr. Muchmore is committed to alternative dispute resolution. He first became involved in ADR by conducting mediations as a Judge Pro Tem for the Maricopa County Superior Court in the early 1980s. He has served as a special master, mediator and arbitrator for the Maricopa County Superior Court. Due to his litigation experience in representing both plaintiffs and defendants, he is frequently selected as a private mediator to assist parties in the evaluation and settlement of their disputes. He also serves as an arbitrator in UM and UIM litigation and other commercial disputes subject to arbitration. "},

        {partner_id: 3, paragraph: "Mr. Muchmore practiced law with the firm of O’Connor, Cavanagh, Anderson, Westover, Killingsworth and Beshears for 17 years. His practice focused almost exclusively on litigation involving insurance defense, including personal injury, professional liability, and insurance coverage disputes. In 1993 he formed Muchmore & Wallwork and Mr. Muchmore began representing plaintiffs in personal injury, professional liability and insurance coverage disputes. In 2003 Mr. Muchmore became Of Counsel at Burch & Cracchiolo, PA where he continued his litigation practice and expanded his ADR practice.  "},

        {partner_id: 3, paragraph: "In January 2015, Mr. Muchmore ceased his litigation practice in order to be a full time neutral with the preeminent Phoenix ADR firm of Scott & Skelly LLC, now Scott, Skelly & Muchmore, LLC. "},

        {partner_id: 3, paragraph: "Mr. Muchmore attended undergraduate school at New Mexico Highlands University, graduating cum laude in 1972 and graduated from the University of New Mexico School of Law in 1976. He is a member of the American Bar Association (Section of Dispute Resolution), the Arizona Bar Association (Litigation and Alternative Dispute Resolution Sections), and the Maricopa County Bar Association (Personal Injury/Negligence Section). Mr. Muchmore is admitted to practice in all courts in the State of Arizona, the Ninth Circuit Court of Appeals, and the Supreme Court of the United States.   "},

        {partner_id: 1, paragraph: "Stephen H. Scott is a former judge on the Arizona Superior Court in Maricopa County, Arizona, who now serves full-time as a mediator, arbitrator, appraisal umpire and discovery master. Prior to serving as a superior court judge, Mr. Scott was a special attorney with the Organized Crime and Racketeering Department of the U.S. Department of Justice and was a trial attorney in private practice. After leaving the Court, Mr. Scott returned to an active civil litigation practice at Gallagher & Kennedy P.A. where he represented both plaintiffs and defendants in personal injury and commercial litigation. Mr. Scott is “AV” rated as a lawyer by Martindale-Hubbe "},

        {partner_id: 1, paragraph: "For approximately the last 20 years, Mr. Scott has served exclusively as mediator, arbitrator, appraisal umpire and discovery master. He mediates more than 200 cases every year and has extensive experience in the following areas: commercial/business, construction, consumer fraud, contract disputes, employment, insurance coverage and bad faith, legal malpractice, medical malpractice and nursing home cases, professional negligence, product liability, personal injury and wrongful death, premises liability, real estate and securities. "},

        {partner_id: 1, paragraph: "Mr. Scott has been a member of the State Bar of Arizona since 1969 and a member of the State Bar of California (inactive) since 1972. He is a member of the Bar of the United States Supreme Court. He is listed in The Best Lawyers in America for Alternative Dispute Resolution and The Lawdragon 500 Leading Judges in America. He received advanced mediation training from JAMS/Endispute and the American Arbitration Association and has lectured at various continuing legal education seminars on the use of ADR to resolve disputes. "},

        {partner_id: 1, paragraph: "Mr. Scott graduated cum laude from Claremont Men’s College (now Claremont McKenna College) and was Order of the Coif at the University of Arizona College of Law (J.D., 1969). "},

        {partner_id: 1, paragraph: "Mr. Scott is also a Charter Member of the Arizona Chapter of the National Academy of Distinguished Neutrals. "},

        {partner_id: 2, paragraph: "Christopher M. Skelly conducts mediations and arbitrations and serves as a special master and discovery master in civil cases. He also serves as an insurance appraisal umpire. Mr. Skelly was a judge on the Arizona Superior Court in Maricopa County from 1993 through 1999. He was the Associate Presiding Judge of the Superior Court in Maricopa County for four of those years, and the Presiding Judge of the Civil Department for two. He also served on civil, criminal and probate calendar assignments. He has conducted thousands of mediations in every kind of civil matter and thousands of civil court proceedings and arbitrations. "},

        {partner_id: 2, paragraph: "Mr. Skelly serves and has served on numerous committees of the courts, state and local bar associations. He chaired the Arizona Commission on Judicial Performance Review and served as the retired judge member of the Arizona Criminal Justice Commission. He is past president of the Arizona Judges Association; former chair of the Arizona State Bar Ethics Committee; former chair of the Arizona State Bar Civil Practice and Procedure Committee; former chair of the Arizona State Bar Civil Jury Instructions Committee; former member of the Arizona Commission on Judicial Conduct; former member of the Arizona State Bar Criminal Rules Committee; former member of the Arizona Juvenile Justice Commission; and former chair of an Arizona State Bar lawyer disciplinary hearing committee. "},

        {partner_id: 2, paragraph: "Mr. Skelly is listed in The Best Lawyers in America for Alternative Dispute Resolution (2011 Phoenix Area ADR Lawyer of the Year, 2012 and 2015 Phoenix Area Arbitration Lawyer of the Year, and 2014 & 2016 Phoenix Area Mediation Lawyer of the Year), The Lawdragon 500 Leading Judges in America, The American Lawyer Top Lawyers, The Phoenix Magazine Top Lawyers, Arizona’s Finest Lawyers, The Best of Arizona Business Attorneys, etc. He is a member of various alternative dispute resolution organizations including the National Academy of Distinguished Neutrals (link), and has participated in hundreds of hours of mediation training as an instructor and a student. "},

        {partner_id: 2, paragraph: "Mr. Skelly practiced law for many years at Fennemore Craig, P.C. in Phoenix. He is an occasional judge pro tem at the Arizona Court of Appeals (Div. 1) and Superior Court in Maricopa County (civil, criminal and probate). He is “AV” rated as a lawyer by Martindale-Hubbell and is a fellow of the Arizona Bar Foundation. Mr. Skelly has taught business law at Phoenix College and has served as an adjunct professor at the Arizona State University College of Law. He has chaired and participated as an instructor in many continuing legal and judicial education training seminars and courses including those sponsored by various bar associations and the Arizona Judicial College. "},

        {partner_id: 2, paragraph: "Mr. Skelly received his B.S. degree in Business Administration from Northern Arizona University in 1980, and his J.D. degree from the University of Arizona in 1983. "},

        {partner_id: 2, paragraph: "Mr. Skelly is a Charter Member of the Arizona Chapter of the National Academy of Distinguished Neutrals. "}
      ]);
    });
};
