
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('bios').del()
    .then(function () {
      // Inserts seed entries
      return knex('bios').insert([
        {partner_id: 2, paragraph: "Charles J. Muchmore has broad and varied litigation and ADR experience that includes handling professional liability, personal injury, product liability, construction, insurance coverage, and commercial litigation matters. Mr. Muchmore has been certified as an Injury and Wrongful Death Litigation Specialist by the Arizona Board of Legal Specialization since 1991. He has been listed in Southwest Super Lawyers since 2009, is included among Arizona’s Finest Lawyers and is an AV® Preeminent 5.0 out of 5.0 peer review rated attorney in Martindale-Hubbell. He is a member of the National Academy of Distinguished Neutrals. " },

        {partner_id: 2, paragraph: "Due to his extensive courtroom experience, Mr. Muchmore was selected as a member of the faculty of the Trial Academy of the International Association of Defense Counsel (IADC). He also has been a featured speaker on toxic tort matters at seminars sponsored by the IADC, the Association of Trial Lawyers of America, the State Bar of Arizona, the Arizona Trial Lawyers Association and the Maricopa County Bar Association. He is lead author of the chapter on \"Manager, Shareholder, Officer and Director Liability\" in the Arizona Environmental Law Manual. Mr. Muchmore served as editor for toxic tort and insurance issues of the State Bar's environmental law newsletter and is past chair of a State Bar seminar on toxic tort litigation. Mr. Muchmore has been a leader in the use of technology in the practice of law and has been appointed as a special master in discovery of electronically stored information. " },

        {partner_id: 2, paragraph: "Mr. Muchmore is committed to alternative dispute resolution. He first became involved in ADR by conducting mediations as a Judge Pro Tem for the Maricopa County Superior Court in the early 1980s. He has served as a special master, mediator and arbitrator for the Maricopa County Superior Court. Due to his litigation experience in representing both plaintiffs and defendants, he is frequently selected as a private mediator to assist parties in the evaluation and settlement of their disputes. He also serves as an arbitrator in UM and UIM litigation and other commercial disputes subject to arbitration. "},

        {partner_id: 2, paragraph: "Mr. Muchmore practiced law with the firm of O’Connor, Cavanagh, Anderson, Westover, Killingsworth and Beshears for 17 years. His practice focused almost exclusively on litigation involving insurance defense, including personal injury, professional liability, and insurance coverage disputes. In 1993 he formed Muchmore & Wallwork and Mr. Muchmore began representing plaintiffs in personal injury, professional liability and insurance coverage disputes. In 2003 Mr. Muchmore became Of Counsel at Burch & Cracchiolo, PA where he continued his litigation practice and expanded his ADR practice.  "},

        {partner_id: 2, paragraph: "In January 2015, Mr. Muchmore ceased his litigation practice in order to be a full time neutral with the preeminent Phoenix ADR firm of Scott & Skelly LLC, now Scott, Skelly & Muchmore, LLC. "},

        {partner_id: 2, paragraph: "Mr. Muchmore attended undergraduate school at New Mexico Highlands University, graduating cum laude in 1972 and graduated from the University of New Mexico School of Law in 1976. He is a member of the American Bar Association (Section of Dispute Resolution), the Arizona Bar Association (Litigation and Alternative Dispute Resolution Sections), and the Maricopa County Bar Association (Personal Injury/Negligence Section). Mr. Muchmore is admitted to practice in all courts in the State of Arizona, the Ninth Circuit Court of Appeals, and the Supreme Court of the United States.   "},

        {partner_id: 1, paragraph: "Christopher M. Skelly conducts mediations and arbitrations and serves as a special master and discovery master in civil cases. He also serves as an insurance appraisal umpire. Mr. Skelly was a judge on the Arizona Superior Court in Maricopa County from 1993 through 1999. He was the Associate Presiding Judge of the Superior Court in Maricopa County for four of those years, and the Presiding Judge of the Civil Department for two. He also served on civil, criminal and probate calendar assignments. He has conducted thousands of mediations in every kind of civil matter and thousands of civil court proceedings and arbitrations. "},

        {partner_id: 1, paragraph: "Mr. Skelly serves and has served on numerous committees of the courts, state and local bar associations. He chaired the Arizona Commission on Judicial Performance Review and served as the retired judge member of the Arizona Criminal Justice Commission. He is past president of the Arizona Judges Association; former chair of the Arizona State Bar Ethics Committee; former chair of the Arizona State Bar Civil Practice and Procedure Committee; former chair of the Arizona State Bar Civil Jury Instructions Committee; former member of the Arizona Commission on Judicial Conduct; former member of the Arizona State Bar Criminal Rules Committee; former member of the Arizona Juvenile Justice Commission; and former chair of an Arizona State Bar lawyer disciplinary hearing committee. "},

        {partner_id: 1, paragraph: "Mr. Skelly is listed in The Best Lawyers in America for Alternative Dispute Resolution (2011 Phoenix Area ADR Lawyer of the Year, 2012 and 2015 Phoenix Area Arbitration Lawyer of the Year, and 2014 & 2016 Phoenix Area Mediation Lawyer of the Year), The Lawdragon 500 Leading Judges in America, The American Lawyer Top Lawyers, The Phoenix Magazine Top Lawyers, Arizona’s Finest Lawyers, The Best of Arizona Business Attorneys, etc. He is a member of various alternative dispute resolution organizations including the National Academy of Distinguished Neutrals (link), and has participated in hundreds of hours of mediation training as an instructor and a student. "},

        {partner_id: 1, paragraph: "Mr. Skelly practiced law for many years at Fennemore Craig, P.C. in Phoenix. He is an occasional judge pro tem at the Arizona Court of Appeals (Div. 1) and Superior Court in Maricopa County (civil, criminal and probate). He is “AV” rated as a lawyer by Martindale-Hubbell and is a fellow of the Arizona Bar Foundation. Mr. Skelly has taught business law at Phoenix College and has served as an adjunct professor at the Arizona State University College of Law. He has chaired and participated as an instructor in many continuing legal and judicial education training seminars and courses including those sponsored by various bar associations and the Arizona Judicial College. "},

        {partner_id: 1, paragraph: "Robert Oberbillig serves as a mediator, arbitrator, and discovery master in civil cases. He has extensive experience in the following areas: medical malpractice, personal injury, nursing home cases, product liability, premises liability, wrongful death, bad faith, defamation, commercial matters, business dissolutions, construction, real estate, probate, and family law. Mr. Oberbillig served 19 years as a trial judge on the Arizona Superior Court in Maricopa County. He served 11 years on the civil assignment and was the Presiding Judge of the Civil Department for three years. Mr. Oberbillig also served on the criminal, family, and juvenile assignments and presided over high profile probate cases.  "},

        {partner_id: 1, paragraph: "Mr. Oberbillig was the designated “settlement judge” for the entire civil department for nine years. In that role, he conducted hundreds of settlement conferences involving serious injury torts and commercial matters. He also regularly held settlement conferences throughout all of his judicial assignments. He has presided over hundreds of jury trials and bench trials. "},

        {partner_id: 3, paragraph: "Mr. Oberbillig was the designated “settlement judge” for the entire civil department for nine years. In that role, he conducted hundreds of settlement conferences involving serious injury torts and commercial matters. He also regularly held settlement conferences throughout all of his judicial assignments. He has presided over hundreds of jury trials and bench trials. "},

        {partner_id: 3, paragraph: "Mr. Oberbillig received the ‘Judge of the Year’ award from the Phoenix Chapter of the American Board of Trial Advocates (ABOTA) in recognition of his extensive experience as a trial judge and for conducting successful settlement conferences. ABOTA is made up of both distinguished plaintiffs’ and defense trial lawyers. He also received the annual ‘Judicial Excellence’ award from the Arizona Association of Defense Counsel. "},

        {partner_id: 3, paragraph: "Mr. Oberbillig was a Martindale-Hubbell ‘AV’ rated attorney before being appointed to the Superior Court. He practiced law for 13 years at Snell and Wilmer and for three years at Doyle Winthrop Oberbillig and West, P.C. His trial/litigation practice focused on both serious personal injury matters and a wide variety of business/contract disputes. Mr. Oberbillig was also extensively involved in ADR as an advocate and a privately retained mediator and arbitrator."},

        {partner_id: 3, paragraph: "Mr. Oberbillig served as a chair of the Maricopa County Bench/Bar Committee and a chair of the Civil Study Committee. He was a member of the Civil Practice and Procedure Committee and a member of the Judicial Executive Committee. He regularly serves as a speaker at numerous continuing legal and judicial education seminars, including several that involve how to effectively advocate in or conduct judicial settlement conferences. "},

        {partner_id: 3, paragraph: "Mr. Oberbillig received his JD from the University of Iowa School of Law with High Distinction in 1982, where he also served as Editor in Chief of the Iowa Law Review. At graduation, Mr. Oberbillig was the sole recipient of the Iowa State Bar Scholastic Achievement, Contribution, and Leadership Award."},

        {partner_id: 3, paragraph: "Mr. Oberbillig is admitted to practice in all state and federal courts of Arizona, the Court of Appeals for the Ninth Circuit, and the Supreme Court of the United States."},

      ]);
    });
};
